In [85]:
# Importando o Pandas
import pandas as pd

In [86]:
#Vizualizando a base de treino

treino = pd.read_csv('train.csv')
treino.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [87]:
# verificando informações da base

treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [88]:
#verificando o tipo dos dados

treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [89]:
# verificando valores nulos

treino.isnull().sum().sort_values(ascending = False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
dtype: int64

In [90]:
# visualizando base de teste

teste = pd.read_csv('test.csv')
teste.head(3)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [91]:
# verificando informações da base

teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [92]:
#verificando o tipo dos dados

teste.dtypes.value_counts()

object     5
int64      4
float64    2
Name: count, dtype: int64

In [93]:
# verificando valores nulos

teste.isnull().sum().sort_values(ascending = False).head(5)

Cabin          327
Age             86
Fare             1
PassengerId      0
Pclass           0
dtype: int64

Temos colunas que possuem valores vazios na base de teste que nao estao vazias na base de treino( dessa maneira devemos tratar esse dados somente na base de teste

Realizando tratamento iniciais dos dados

In [94]:
# verificando os valores vazios na base de treino

treino.isnull().sum().sort_values(ascending = False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
dtype: int64

In [95]:
#retornando o tamanho da base de treino
treino.shape

(891, 12)

In [96]:
#vizualizando noavmente a base
treino.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [97]:
# verificando cardinalidade dos dados 

treino.nunique().sort_values(ascending = False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Pclass           3
Embarked         3
Survived         2
Sex              2
dtype: int64

In [98]:
# eliminando colunas da base de treino

treino = treino.drop(['Name', 'Ticket', 'Cabin'], axis = 1)

In [99]:
# eliminando colunas para a base de teste
teste = teste.drop(['Name', 'Ticket', 'Cabin'], axis = 1)

In [100]:
# verificando a media de idade para a base de treino

treino.Age.mean()

29.69911764705882

In [101]:
# selecionando colunas com idade vazia e colocando a media de idade na base de treino

treino.loc[treino.Age.isnull(),'Age'] = treino.Age.mean()

In [102]:
# selecionando colunas com idade vazia e colocando a media de idade na base de teste

teste.loc[teste.Age.isnull(),'Age'] = teste.Age.mean()

Trabalhando as colunas de texto

In [103]:
# vendo as colunas de texto do dataset de treino

treino.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Sex             True
Age            False
SibSp          False
Parch          False
Fare           False
Embarked        True
dtype: bool

In [104]:
# vendo as colunas de texto do dataset de treino

treino.columns[treino.dtypes == 'object']

Index(['Sex', 'Embarked'], dtype='object')

In [105]:
# verificando os valores da coluna sex

treino.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [106]:
# verificando os valores da coluna embarked

treino.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [107]:
# utilizando uma lambda function para fazer o tratamento , criando uma nova coluna chamada Male_Check que recebe 1 para male e 0 para female no dataset de treino

treino['MaleCheck'] = treino.Sex.apply(lambda x: 1 if x == 'male' else 0)

In [108]:
# verificando valores da coluna Sex e MaleCheck no dataset de treino

treino[['Sex', 'MaleCheck']].value_counts()

Sex     MaleCheck
male    1            577
female  0            314
Name: count, dtype: int64

In [109]:
# utilizando uma lambda function para fazer o tratamento , criando uma nova coluna chamada Male_Check que recebe 1 para male e 0 para female no dataset de test

teste['MaleCheck'] = teste.Sex.apply(lambda x: 1 if x == 'male' else 0)

In [110]:
# verificando valores da coluna Sex e MaleCheck no dataset de teste

teste[['Sex', 'MaleCheck']].value_counts()

Sex     MaleCheck
male    1            266
female  0            152
Name: count, dtype: int64

Trabalhando a coluna de embarked - utlizando o OneHotEncoder

In [111]:
# selecionando a moda da coluna embarked


treino.Embarked.mode()
treino.Embarked.mode()[0]

'S'

In [112]:
# substituindo valores vazios da coluna embarked pela moda encontrada

treino.loc[treino.Embarked.isnull(),'Embarked'] = treino.Embarked.mode()[0]

In [113]:
treino.Embarked.value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [114]:
# importando o OneHotEncoder

from sklearn.preprocessing import OneHotEncoder

In [115]:
# criar encoder

ohe = OneHotEncoder(handle_unknown='ignore')

In [116]:
# fazer o fit com os dados

ohe = ohe.fit(treino[['Embarked']])

In [117]:
# fazendo a transformação dos dados

ohe.transform(treino[['Embarked']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [118]:
ohe_df = pd.DataFrame(ohe.transform(treino[['Embarked']]).toarray(), columns = ohe.get_feature_names_out())

In [119]:
ohe_df

     Embarked_C  Embarked_Q  Embarked_S
0           0.0         0.0         1.0
1           1.0         0.0         0.0
2           0.0         0.0         1.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
..          ...         ...         ...
886         0.0         0.0         1.0
887         0.0         0.0         1.0
888         0.0         0.0         1.0
889         1.0         0.0         0.0
890         0.0         1.0         0.0

[891 rows x 3 columns]

In [120]:
# adicionando o  ohe_df na base de treino

treino = pd.concat([treino, ohe_df], axis =1)

In [121]:
# fazendo o mesmo para a coluna de teste

ohe = ohe.fit(teste[['Embarked']])

In [122]:
# fazendo a transformação dos dados

ohe.transform(teste[['Embarked']]).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [123]:
ohe_df = pd.DataFrame(ohe.transform(teste[['Embarked']]).toarray(), columns = ohe.get_feature_names_out())

In [124]:
ohe_df

     Embarked_C  Embarked_Q  Embarked_S
0           0.0         1.0         0.0
1           0.0         0.0         1.0
2           0.0         1.0         0.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
..          ...         ...         ...
413         0.0         0.0         1.0
414         1.0         0.0         0.0
415         0.0         0.0         1.0
416         0.0         0.0         1.0
417         1.0         0.0         0.0

[418 rows x 3 columns]

In [125]:
# adicionando o  ohe_df na base de teste

teste = pd.concat([teste, ohe_df], axis =1)

In [126]:
teste.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,892,3,male,34.5,0,0,7.8292,Q,1,0.0,1.0,0.0
1,893,3,female,47.0,1,0,7.0000,S,0,0.0,0.0,1.0
2,894,2,male,62.0,0,0,9.6875,Q,1,0.0,1.0,0.0
3,895,3,male,27.0,0,0,8.6625,S,1,0.0,0.0,1.0
4,896,3,female,22.0,1,1,12.2875,S,0,0.0,0.0,1.0

In [127]:
treino.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.2500,S,1,0.0,0.0,1.0
1,2,1,1,female,38.0,1,0,71.2833,C,0,1.0,0.0,0.0
2,3,1,3,female,26.0,0,0,7.9250,S,0,0.0,0.0,1.0
3,4,1,1,female,35.0,1,0,53.1000,S,0,0.0,0.0,1.0
4,5,0,3,male,35.0,0,0,8.0500,S,1,0.0,0.0,1.0

In [128]:
# verificando a media da coluna fare para a base de teste

teste.loc[teste.Fare.isnull(),'Fare']

152   NaN
Name: Fare, dtype: float64

In [129]:
# substituindo valor vazio pela media da coluna Fare

teste.loc[teste.Fare.isnull(),'Fare'] = teste.Fare.mean()

verificando novamente os dados vazios

In [130]:
#base de treino

treino.isnull().sum().sort_values(ascending = False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [131]:
#base de teste

teste.isnull().sum().sort_values(ascending = False).head(5)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

In [132]:
#verificando as colunas de treino na base de treino

treino.columns[treino.dtypes != 'object']

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'MaleCheck', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [133]:
# criando uma nova base de treino somente com valores numericos

treino_nr = treino.loc[:, treino.columns[treino.dtypes != 'object']]

In [134]:
#verificando as colunas de teste na base de treino

teste.columns[teste.dtypes != 'object']

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'MaleCheck',
       'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [135]:
# criando uma nova base de teste somente com valores numericos

teste_nr = teste.loc[:, teste.columns[teste.dtypes != 'object']]

In [136]:
# verificando base de treino somente com dados numericos
treino_nr.head(3)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,1,0.0,0.0,1.0
1,2,1,1,38.0,1,0,71.2833,0,1.0,0.0,0.0
2,3,1,3,26.0,0,0,7.9250,0,0.0,0.0,1.0

In [141]:
# verificando base de teste somente com dados numericos
teste_nr.head(3)

,PassengerId,Pclass,Age,SibSp,Parch,Fare,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,892,3,34.5,0,0,7.8292,1,0.0,1.0,0.0
1,893,3,47.0,1,0,7.0000,0,0.0,0.0,1.0
2,894,2,62.0,0,0,9.6875,1,0.0,1.0,0.0

In [138]:
treino.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.2500,S,1,0.0,0.0,1.0
1,2,1,1,female,38.0,1,0,71.2833,C,0,1.0,0.0,0.0
2,3,1,3,female,26.0,0,0,7.9250,S,0,0.0,0.0,1.0

In [139]:
treino = treino.drop(['Sex', 'Embarked'], axis = 1)

In [140]:
treino.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,1,0.0,0.0,1.0
1,2,1,1,38.0,1,0,71.2833,0,1.0,0.0,0.0
2,3,1,3,26.0,0,0,7.9250,0,0.0,0.0,1.0
3,4,1,1,35.0,1,0,53.1000,0,0.0,0.0,1.0
4,5,0,3,35.0,0,0,8.0500,1,0.0,0.0,1.0

Criando modelo para classificar os dados

In [142]:
# importando train_test_split

from sklearn.model_selection import train_test_split

In [143]:
#separando base de treino em x e y

x = treino_nr.drop(['PassengerId','Survived'], axis = 1)
y = treino.Survived

In [144]:
# separando em treino e validação

x_train, x_val , y_train , y_val = train_test_split(x,y, test_size = 0.2, random_state = 42)

Decision Tree

In [145]:
# fazendo importacao

from sklearn import tree

In [146]:
#criando classificador

clf_arvore = tree.DecisionTreeClassifier(random_state = 42)

In [147]:
#fazendo o fit com os dados

clf_arvore = clf_arvore.fit(x_train,y_train)

In [148]:
# fazendo previsao

y_pred_arvore = clf_arvore.predict(x_val)

KNN

In [149]:
# fazendo importacao

from sklearn.neighbors import KNeighborsClassifier

In [150]:
#criando classificador

clf_knn = KNeighborsClassifier(n_neighbors = 3)

In [151]:
#fazendo o fit com os dados

clf_knn = clf_knn.fit(x_train,y_train)

In [152]:
# fazendo previsao

y_pred_knn = clf_knn.predict(x_val)

Logistic Regression

In [153]:
# fazendo importacao

from sklearn.linear_model import LogisticRegression

In [154]:
#criando classificador

clf_lr = LogisticRegression(random_state=42)

In [155]:
#fazendo o fit com os dados

clf_lr = clf_lr.fit(x_train,y_train)

C:\Users\Leo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [156]:
# fazendo previsao

y_pred_lr = clf_lr.predict(x_val)

Realizando a avaliaçao dos modelos com a acuracia

In [157]:
# importando acuracia

from sklearn.metrics import accuracy_score

In [158]:
# avaliando decison tree
accuracy_score(y_val, y_pred_arvore)

0.7821229050279329

In [159]:
# avaliando knn
accuracy_score(y_val, y_pred_knn)

0.7150837988826816

In [160]:
#avaliando logistic regression
accuracy_score(y_val, y_pred_lr)

0.8044692737430168

avaliando a matriz de confusao

In [161]:
# importando
from sklearn.metrics import confusion_matrix

In [162]:
# avaliando decison tree
confusion_matrix(y_val, y_pred_arvore)

array([[84, 21],
       [18, 56]], dtype=int64)

In [163]:
# avaliando knn
confusion_matrix(y_val, y_pred_knn)

array([[90, 15],
       [36, 38]], dtype=int64)

In [164]:
#avaliando logistic regression
confusion_matrix(y_val, y_pred_lr)

array([[90, 15],
       [20, 54]], dtype=int64)

Fazendo a previsao para os dados de validação com o modelo que teve a melhor acuracia

In [165]:
#vizualizando x_train

x_train.head(3)

,Pclass,Age,SibSp,Parch,Fare,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
331,1,45.5,0,0,28.500,1,0.0,0.0,1.0
733,2,23.0,0,0,13.000,1,0.0,0.0,1.0
382,3,32.0,0,0,7.925,1,0.0,0.0,1.0

In [166]:
# vizualizando base de teste apenas com dados numericos

teste_nr.head(3)

,PassengerId,Pclass,Age,SibSp,Parch,Fare,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,892,3,34.5,0,0,7.8292,1,0.0,1.0,0.0
1,893,3,47.0,1,0,7.0000,0,0.0,0.0,1.0
2,894,2,62.0,0,0,9.6875,1,0.0,1.0,0.0

In [167]:
# para a base de validacao ser igual a de treino temos que eliminar a coluna PassengerId

x_teste = teste_nr.drop('PassengerId', axis = 1)

In [168]:
# vizuanlizando a variavel x_teste criada

x_teste.head(4)

,Pclass,Age,SibSp,Parch,Fare,MaleCheck,Embarked_C,Embarked_Q,Embarked_S
0,3,34.5,0,0,7.8292,1,0.0,1.0,0.0
1,3,47.0,1,0,7.0000,0,0.0,0.0,1.0
2,2,62.0,0,0,9.6875,1,0.0,1.0,0.0
3,3,27.0,0,0,8.6625,1,0.0,0.0,1.0

In [169]:
# utilizando a logistic regression para a validaçao

y_pred = clf_lr.predict(x_teste)

In [170]:
# criando uma nova coluna com a previsao na base de teste

teste['Survived'] = y_pred

In [171]:
# selecioando o id do passageiros e os possiveis sobreviventes de acordo com o modelo
base_final = teste[['PassengerId','Survived']]

In [172]:
# exportando a base em csv

base_final.to_csv('modelo2.csv', index = False)